version: "3"
services:
  haui-chat-backend:
    container_name: haui-chat-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: haui_chat_be
    ports:
      - 9090:9999
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1
    volumes:
      - ./backend/databases/:/app/databases/
      - ./backend/datasets/:/app/datasets/
      - ./model/:/app/model/
    restart: always
    env_file:
      - ./backend/.env
    entrypoint: /bin/sh
    command: -c "ls -l /app/scripts && bash /app/scripts/start.sh"
    networks:
      - haui_chat_be_net

  haui-chat-frontend:
    container_name: haui-chat-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: haui_chat_fe
    ports:
      - 3030:3000
    restart: always
    command: ["npm", "run", "dev"]
    networks:
      - haui_chat_be_net

networks:
  haui_chat_be_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24 